export interface Photo {
  src: string;
  alt: string;
  category: string;
}

// Category mapping: folder names to display names
const categoryMap: Record<string, string> = {
  'blackwhite': 'Black & White',
  'blue_elv': 'Blue Elevator',
  'bug': 'Bug Collection',
  'clear_sky': 'Clear Sky',
  'Confident_Man_Chairs': 'Confident Man Chairs',
  'direct_flash': 'Direct Flash',
  'Elevator_Music': 'Elevator Music',
  'field': 'Field',
  'ghosts_on_the_beach': 'Ghosts On The Beach',
  'glasses-filmstrip_coloring': 'Glasses Filmstrip',
  'highflash': 'High Flash',
  'isuredo': 'I Sure Do',
  'Organ_Grainy': 'Organ Grainy',
  'primary': 'Primary',
};

function generatePhotosForCategory(folder: string, files: string[]): Photo[] {
  const categoryName = categoryMap[folder] || folder;
  return files.map(file => ({
    src: `/images/${folder}/${file}`,
    alt: `${file.replace(/\.jpg$/i, '').replace(/-/g, ' ')} - ${categoryName}`,
    category: categoryName,
  }));
}

// Shuffle function for randomizing photos
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Confident Man Chairs photos
const Confident_Man_ChairsPhotos = generatePhotosForCategory('Confident_Man_Chairs', [
  'untitled-105.jpg',
  'untitled-122-2.jpg',
  'untitled-122.jpg',
  'untitled-127.jpg',
  'untitled-128.jpg',
  'untitled-132-Enhanced-NR.jpg',
  'untitled-132.jpg',
  'untitled-139-Enhanced-NR.jpg',
  'untitled-139.jpg',
  'untitled-150.jpg',
  'untitled-156-2.jpg',
  'untitled-156.jpg',
  'untitled-159.jpg',
  'untitled-161.jpg',
  'untitled-167.jpg',
  'untitled-169.jpg',
  'untitled-181.jpg',
  'untitled-184.jpg',
  'untitled-33.jpg',
  'untitled-34.jpg',
  'untitled-47.jpg',
  'untitled-49.jpg',
  'untitled-50.jpg',
  'untitled-51.jpg',
  'untitled-53.jpg',
  'untitled-57.jpg',
  'untitled-65.jpg',
  'untitled-673.jpg',
  'untitled-680.jpg',
  'untitled-690.jpg',
  'untitled-692.jpg',
  'untitled-708.jpg',
  'untitled-71.jpg',
  'untitled-716.jpg',
  'untitled-718.jpg',
  'untitled-723.jpg',
  'untitled-739.jpg',
  'untitled-75.jpg',
  'untitled-83.jpg',
  'untitled-97.jpg',
]);

// Elevator Music photos
const Elevator_MusicPhotos = generatePhotosForCategory('Elevator_Music', [
  'elevatormusic-10.jpg',
  'elevatormusic-19.jpg',
  'elevatormusic-20.jpg',
  'elevatormusic-21.jpg',
  'elevatormusic-22.jpg',
  'elevatormusic-23.jpg',
  'elevatormusic-24.jpg',
  'elevatormusic-25.jpg',
  'elevatormusic-26.jpg',
  'elevatormusic-27.jpg',
  'elevatormusic-28.jpg',
  'elevatormusic-29.jpg',
  'elevatormusic-30.jpg',
  'elevatormusic-31.jpg',
  'elevatormusic-32.jpg',
  'elevatormusic-33.jpg',
  'elevatormusic-34.jpg',
  'elevatormusic-35.jpg',
  'elevatormusic-36.jpg',
  'elevatormusic-37.jpg',
  'elevatormusic-38.jpg',
  'elevatormusic-39.jpg',
  'elevatormusic-40.jpg',
  'elevatormusic-41.jpg',
  'elevatormusic-42.jpg',
  'elevatormusic-43.jpg',
  'elevatormusic-44.jpg',
  'elevatormusic-45.jpg',
  'elevatormusic-53.jpg',
  'elevatormusic-54.jpg',
  'elevatormusic-55.jpg',
  'elevatormusic-56.jpg',
  'elevatormusic-57.jpg',
  'elevatormusic-58.jpg',
  'elevatormusic-59.jpg',
  'elevatormusic-60.jpg',
  'elevatormusic-61.jpg',
  'elevatormusic-62.jpg',
  'elevatormusic-63.jpg',
  'elevatormusic-64.jpg',
  'elevatormusic-65.jpg',
  'elevatormusic-66.jpg',
  'elevatormusic-70.jpg',
  'elevatormusic-71.jpg',
  'elevatormusic-72.jpg',
  'elevatormusic-73.jpg',
  'elevatormusic-74.jpg',
  'elevatormusic-75.jpg',
  'elevatormusic-76.jpg',
  'elevatormusic-77.jpg',
  'elevatormusic-78.jpg',
  'elevatormusic-79.jpg',
  'elevatormusic-80.jpg',
  'elevatormusic-91.jpg',
]);

// Organ Grainy photos
const Organ_GrainyPhotos = generatePhotosForCategory('Organ_Grainy', [
  'curiousman-photobyjoy-7.jpg',
  'curiousman-photobyjoy-8.jpg',
  'untitled-285.jpg',
  'untitled-288.jpg',
  'untitled-291.jpg',
  'untitled-305.jpg',
  'untitled-306.jpg',
  'untitled-320.jpg',
  'untitled-336.jpg',
]);

// Black & White photos
const blackwhitePhotos = generatePhotosForCategory('blackwhite', [
  'curiousman-photobyjoy-10.jpg',
  'curiousman-photobyjoy-2.jpg',
  'curiousman-photobyjoy-29.jpg',
  'curiousman-photobyjoy-3.jpg',
  'curiousman-photobyjoy-35.jpg',
  'curiousman-photobyjoy-36.jpg',
  'curiousman-photobyjoy-37.jpg',
  'curiousman-photobyjoy-38.jpg',
  'curiousman-photobyjoy-4.jpg',
  'curiousman-photobyjoy-47.jpg',
  'curiousman-photobyjoy-49.jpg',
  'curiousman-photobyjoy-5.jpg',
  'curiousman-photobyjoy-50.jpg',
  'curiousman-photobyjoy-51.jpg',
  'curiousman-photobyjoy-52.jpg',
  'curiousman-photobyjoy-53.jpg',
  'curiousman-photobyjoy-6.jpg',
  'curiousman-photobyjoy-9.jpg',
]);

// Blue Elevator photos
const blue_elvPhotos = generatePhotosForCategory('blue_elv', [
  'elevatormusic-2.jpg',
  'elevatormusic-3.jpg',
  'elevatormusic-4.jpg',
  'elevatormusic-67.jpg',
  'elevatormusic-68.jpg',
  'elevatormusic-69.jpg',
  'elevatormusic-70.jpg',
  'elevatormusic.jpg',
]);

// Bug Collection photos
const bugPhotos = generatePhotosForCategory('bug', [
  'raybug-10.jpg',
  'raybug-11.jpg',
  'raybug-12.jpg',
  'raybug-13.jpg',
  'raybug-14.jpg',
  'raybug-15.jpg',
  'raybug-16.jpg',
  'raybug-17.jpg',
  'raybug-18.jpg',
  'raybug-19.jpg',
  'raybug-2.jpg',
  'raybug-20.jpg',
  'raybug-21.jpg',
  'raybug-22.jpg',
  'raybug-23.jpg',
  'raybug-24.jpg',
  'raybug-25.jpg',
  'raybug-26.jpg',
  'raybug-27.jpg',
  'raybug-28.jpg',
  'raybug-29.jpg',
  'raybug-3.jpg',
  'raybug-30.jpg',
  'raybug-31.jpg',
  'raybug-32.jpg',
  'raybug-33.jpg',
  'raybug-34.jpg',
  'raybug-35.jpg',
  'raybug-36.jpg',
  'raybug-37.jpg',
  'raybug-38.jpg',
  'raybug-39.jpg',
  'raybug-4.jpg',
  'raybug-40.jpg',
  'raybug-41.jpg',
  'raybug-42.jpg',
  'raybug-43.jpg',
  'raybug-44.jpg',
  'raybug-45.jpg',
  'raybug-46.jpg',
  'raybug-47.jpg',
  'raybug-48.jpg',
  'raybug-49.jpg',
  'raybug-5.jpg',
  'raybug-50.jpg',
  'raybug-51.jpg',
  'raybug-52.jpg',
  'raybug-53.jpg',
  'raybug-54.jpg',
  'raybug-55.jpg',
  'raybug-56.jpg',
  'raybug-57.jpg',
  'raybug-58.jpg',
  'raybug-59.jpg',
  'raybug-6.jpg',
  'raybug-60.jpg',
  'raybug-61.jpg',
  'raybug-62.jpg',
  'raybug-63.jpg',
  'raybug-64.jpg',
  'raybug-65.jpg',
  'raybug-66.jpg',
  'raybug-67.jpg',
  'raybug-68.jpg',
  'raybug-69.jpg',
  'raybug-7.jpg',
  'raybug-70.jpg',
  'raybug-71.jpg',
  'raybug-72.jpg',
  'raybug-73.jpg',
  'raybug-74.jpg',
  'raybug-75.jpg',
  'raybug-76.jpg',
  'raybug-77.jpg',
  'raybug-78.jpg',
  'raybug-8.jpg',
  'raybug-9.jpg',
  'raybug.jpg',
]);

// Clear Sky photos
const clear_skyPhotos = generatePhotosForCategory('clear_sky', [
  'clearsky-10.jpg',
  'clearsky-11.jpg',
  'clearsky-12.jpg',
  'clearsky-13.jpg',
  'clearsky-14.jpg',
  'clearsky-15.jpg',
  'clearsky-16.jpg',
  'clearsky-17.jpg',
  'clearsky-18.jpg',
  'clearsky-19.jpg',
  'clearsky-2.jpg',
  'clearsky-20.jpg',
  'clearsky-21.jpg',
  'clearsky-22.jpg',
  'clearsky-23.jpg',
  'clearsky-24.jpg',
  'clearsky-25.jpg',
  'clearsky-26.jpg',
  'clearsky-27.jpg',
  'clearsky-28.jpg',
  'clearsky-29.jpg',
  'clearsky-3.jpg',
  'clearsky-30.jpg',
  'clearsky-31.jpg',
  'clearsky-32.jpg',
  'clearsky-33.jpg',
  'clearsky-34.jpg',
  'clearsky-35.jpg',
  'clearsky-36.jpg',
  'clearsky-37.jpg',
  'clearsky-38.jpg',
  'clearsky-39.jpg',
  'clearsky-4.jpg',
  'clearsky-5.jpg',
  'clearsky-6.jpg',
  'clearsky-7.jpg',
  'clearsky-8.jpg',
  'clearsky-9.jpg',
  'clearsky.jpg',
]);

// Direct Flash photos
const direct_flashPhotos = generatePhotosForCategory('direct_flash', [
  'elevatormusic-46.jpg',
  'elevatormusic-47.jpg',
  'elevatormusic-48.jpg',
  'elevatormusic-49.jpg',
  'elevatormusic-50.jpg',
  'elevatormusic-51.jpg',
  'elevatormusic-52.jpg',
  'elevatormusic-81.jpg',
  'elevatormusic-82.jpg',
  'elevatormusic-83.jpg',
  'elevatormusic-84.jpg',
  'elevatormusic-85.jpg',
  'elevatormusic-86.jpg',
  'elevatormusic-87.jpg',
  'elevatormusic-88.jpg',
  'elevatormusic-89.jpg',
  'elevatormusic-90.jpg',
]);

// Field photos
const fieldPhotos = generatePhotosForCategory('field', [
  'rayfield-10.jpg',
  'rayfield-11.jpg',
  'rayfield-12.jpg',
  'rayfield-13.jpg',
  'rayfield-14.jpg',
  'rayfield-15.jpg',
  'rayfield-16.jpg',
  'rayfield-17.jpg',
  'rayfield-18.jpg',
  'rayfield-19.jpg',
  'rayfield-2.jpg',
  'rayfield-20.jpg',
  'rayfield-21.jpg',
  'rayfield-22.jpg',
  'rayfield-23.jpg',
  'rayfield-24.jpg',
  'rayfield-25.jpg',
  'rayfield-26.jpg',
  'rayfield-27.jpg',
  'rayfield-28.jpg',
  'rayfield-29.jpg',
  'rayfield-3.jpg',
  'rayfield-30.jpg',
  'rayfield-31.jpg',
  'rayfield-32.jpg',
  'rayfield-33.jpg',
  'rayfield-34.jpg',
  'rayfield-35.jpg',
  'rayfield-36.jpg',
  'rayfield-37.jpg',
  'rayfield-38.jpg',
  'rayfield-39.jpg',
  'rayfield-4.jpg',
  'rayfield-40.jpg',
  'rayfield-41.jpg',
  'rayfield-42.jpg',
  'rayfield-43.jpg',
  'rayfield-44.jpg',
  'rayfield-45.jpg',
  'rayfield-46.jpg',
  'rayfield-47.jpg',
  'rayfield-48.jpg',
  'rayfield-49.jpg',
  'rayfield-5.jpg',
  'rayfield-50.jpg',
  'rayfield-51.jpg',
  'rayfield-52.jpg',
  'rayfield-53.jpg',
  'rayfield-54.jpg',
  'rayfield-55.jpg',
  'rayfield-56.jpg',
  'rayfield-57.jpg',
  'rayfield-58.jpg',
  'rayfield-59.jpg',
  'rayfield-6.jpg',
  'rayfield-60.jpg',
  'rayfield-61.jpg',
  'rayfield-62.jpg',
  'rayfield-63.jpg',
  'rayfield-7.jpg',
  'rayfield-8.jpg',
  'rayfield-9.jpg',
  'rayfield.jpg',
]);

// Ghosts On The Beach photos
const ghosts_on_the_beachPhotos = generatePhotosForCategory('ghosts_on_the_beach', [
  'beachghosts-10.jpg',
  'beachghosts-11.jpg',
  'beachghosts-12.jpg',
  'beachghosts-13.jpg',
  'beachghosts-14.jpg',
  'beachghosts-15.jpg',
  'beachghosts-16.jpg',
  'beachghosts-17.jpg',
  'beachghosts-18.jpg',
  'beachghosts-19.jpg',
  'beachghosts-2.jpg',
  'beachghosts-20.jpg',
  'beachghosts-21.jpg',
  'beachghosts-22.jpg',
  'beachghosts-23.jpg',
  'beachghosts-24.jpg',
  'beachghosts-25.jpg',
  'beachghosts-26.jpg',
  'beachghosts-27.jpg',
  'beachghosts-28.jpg',
  'beachghosts-29.jpg',
  'beachghosts-3.jpg',
  'beachghosts-30.jpg',
  'beachghosts-31.jpg',
  'beachghosts-32.jpg',
  'beachghosts-33.jpg',
  'beachghosts-34.jpg',
  'beachghosts-35.jpg',
  'beachghosts-36.jpg',
  'beachghosts-37.jpg',
  'beachghosts-38.jpg',
  'beachghosts-39.jpg',
  'beachghosts-4.jpg',
  'beachghosts-40.jpg',
  'beachghosts-41.jpg',
  'beachghosts-42.jpg',
  'beachghosts-43.jpg',
  'beachghosts-44.jpg',
  'beachghosts-45.jpg',
  'beachghosts-46.jpg',
  'beachghosts-5.jpg',
  'beachghosts-6.jpg',
  'beachghosts-7.jpg',
  'beachghosts-8.jpg',
  'beachghosts-9.jpg',
  'beachghosts.jpg',
]);

// Glasses Filmstrip photos
const glasses_filmstrip_coloringPhotos = generatePhotosForCategory('glasses-filmstrip_coloring', [
  'curiousman-photobyjoy-54.jpg',
  'curiousman-photobyjoy-55.jpg',
  'curiousman-photobyjoy-56.jpg',
  'curiousman-photobyjoy-57.jpg',
  'curiousman-photobyjoy-58.jpg',
  'curiousman-photobyjoy-59.jpg',
  'curiousman-photobyjoy-60.jpg',
  'curiousman-photobyjoy-61.jpg',
  'curiousman-photobyjoy-62.jpg',
  'curiousman-photobyjoy-63.jpg',
  'curiousman-photobyjoy-64.jpg',
  'curiousman-photobyjoy-65.jpg',
  'curiousman-photobyjoy-66.jpg',
  'curiousman-photobyjoy-67.jpg',
  'curiousman-photobyjoy-68.jpg',
  'curiousman-photobyjoy-69.jpg',
  'curiousman-photobyjoy-70.jpg',
  'curiousman-photobyjoy-71.jpg',
  'curiousman-photobyjoy-72.jpg',
  'curiousman-photobyjoy-73.jpg',
  'curiousman-photobyjoy.jpg',
]);

// High Flash photos
const highflashPhotos = generatePhotosForCategory('highflash', [
  'elevatormusic-10.jpg',
  'elevatormusic-11.jpg',
  'elevatormusic-12.jpg',
  'elevatormusic-13.jpg',
  'elevatormusic-14.jpg',
  'elevatormusic-15.jpg',
  'elevatormusic-16.jpg',
  'elevatormusic-17.jpg',
  'elevatormusic-18.jpg',
  'elevatormusic-5.jpg',
  'elevatormusic-6.jpg',
  'elevatormusic-7.jpg',
  'elevatormusic-8.jpg',
  'elevatormusic-9.jpg',
]);

// I Sure Do photos
const isuredoPhotos = generatePhotosForCategory('isuredo', [
  'isuredo-10.jpg',
  'isuredo-12.jpg',
  'isuredo-13.jpg',
  'isuredo-14.jpg',
  'isuredo-15.jpg',
  'isuredo-16.jpg',
  'isuredo-17.jpg',
  'isuredo-18.jpg',
  'isuredo-19.jpg',
  'isuredo-2.jpg',
  'isuredo-20.jpg',
  'isuredo-21.jpg',
  'isuredo-22.jpg',
  'isuredo-23.jpg',
  'isuredo-24.jpg',
  'isuredo-25.jpg',
  'isuredo-26.jpg',
  'isuredo-27.jpg',
  'isuredo-28.jpg',
  'isuredo-29.jpg',
  'isuredo-3.jpg',
  'isuredo-30.jpg',
  'isuredo-31.jpg',
  'isuredo-32.jpg',
  'isuredo-34.jpg',
  'isuredo-35.jpg',
  'isuredo-36.jpg',
  'isuredo-37.jpg',
  'isuredo-38.jpg',
  'isuredo-39.jpg',
  'isuredo-4.jpg',
  'isuredo-40.jpg',
  'isuredo-41.jpg',
  'isuredo-42.jpg',
  'isuredo-43.jpg',
  'isuredo-44.jpg',
  'isuredo-45.jpg',
  'isuredo-46.jpg',
  'isuredo-47.jpg',
  'isuredo-48.jpg',
  'isuredo-49.jpg',
  'isuredo-5.jpg',
  'isuredo-50.jpg',
  'isuredo-51.jpg',
  'isuredo-52.jpg',
  'isuredo-53.jpg',
  'isuredo-54.jpg',
  'isuredo-55.jpg',
  'isuredo-56.jpg',
  'isuredo-57.jpg',
  'isuredo-58.jpg',
  'isuredo-59.jpg',
  'isuredo-6.jpg',
  'isuredo-60.jpg',
  'isuredo-61.jpg',
  'isuredo-62.jpg',
  'isuredo-64.jpg',
  'isuredo-66.jpg',
  'isuredo-67.jpg',
  'isuredo-68.jpg',
  'isuredo-69.jpg',
  'isuredo-7.jpg',
  'isuredo-71.jpg',
  'isuredo-72.jpg',
  'isuredo-73.jpg',
  'isuredo-74.jpg',
  'isuredo-75.jpg',
  'isuredo-76.jpg',
  'isuredo-77.jpg',
  'isuredo-78.jpg',
  'isuredo-79.jpg',
  'isuredo-8.jpg',
  'isuredo-80.jpg',
  'isuredo-9.jpg',
  'isuredo.jpg',
]);

// Primary photos
const primaryPhotos = generatePhotosForCategory('primary', [
  'curiousman-photobyjoy-11.jpg',
  'curiousman-photobyjoy-12.jpg',
  'curiousman-photobyjoy-13.jpg',
  'curiousman-photobyjoy-21.jpg',
  'curiousman-photobyjoy-22.jpg',
  'curiousman-photobyjoy-23.jpg',
  'curiousman-photobyjoy-24.jpg',
  'curiousman-photobyjoy-25.jpg',
  'curiousman-photobyjoy-26.jpg',
  'curiousman-photobyjoy-27.jpg',
  'curiousman-photobyjoy-28.jpg',
  'curiousman-photobyjoy-30.jpg',
  'curiousman-photobyjoy-31.jpg',
  'curiousman-photobyjoy-32.jpg',
  'curiousman-photobyjoy-33.jpg',
  'curiousman-photobyjoy-34.jpg',
  'curiousman-photobyjoy-39.jpg',
  'curiousman-photobyjoy-40.jpg',
  'curiousman-photobyjoy-41.jpg',
  'curiousman-photobyjoy-42.jpg',
  'curiousman-photobyjoy-43.jpg',
  'curiousman-photobyjoy-44.jpg',
  'curiousman-photobyjoy-45.jpg',
  'curiousman-photobyjoy-46.jpg',
  'curiousman-photobyjoy-48.jpg',
]);

// Combine all photos
export const allPhotos: Photo[] = [
  ...Confident_Man_ChairsPhotos,
  ...Elevator_MusicPhotos,
  ...Organ_GrainyPhotos,
  ...blackwhitePhotos,
  ...blue_elvPhotos,
  ...bugPhotos,
  ...clear_skyPhotos,
  ...direct_flashPhotos,
  ...fieldPhotos,
  ...ghosts_on_the_beachPhotos,
  ...glasses_filmstrip_coloringPhotos,
  ...highflashPhotos,
  ...isuredoPhotos,
  ...primaryPhotos
];

// Get all unique categories
export const allCategories: string[] = Object.values(categoryMap);

// Get featured photos for home page (selecting diverse, high-impact photos)
export const featuredPhotos: Photo[] = [
  // Primary collection (professional/promotional)
  ...primaryPhotos.slice(0, 2),
  // Black & White (artistic)
  ...blackwhitePhotos.slice(2, 4),
  // Ghosts On The Beach (atmospheric)
  ...ghosts_on_the_beachPhotos.slice(0, 2),
  // Field or Clear Sky (outdoor/natural)
  ...fieldPhotos.slice(0, 1),
  ...clear_skyPhotos.slice(0, 1),
  // Other collections for variety
  ...Elevator_MusicPhotos.slice(5, 6),
  ...bugPhotos.slice(10, 11),
].slice(0, 9); // Limit to 9 photos

// Get photos by category
export function getPhotosByCategory(category: string): Photo[] {
  return allPhotos.filter(photo => photo.category === category);
}

// Select background photos for home page hero section
// Choosing atmospheric, high-quality photos that work well as backgrounds
export const backgroundPhotos: Photo[] = [
  ...primaryPhotos.slice(0, 1),
  ...blackwhitePhotos.slice(5, 6),
  ...ghosts_on_the_beachPhotos.slice(10, 11),
  ...fieldPhotos.slice(15, 16),
  ...clear_skyPhotos.slice(5, 6),
].slice(0, 5);
